import { Footer } from "./components/footer"
import { Header } from "./components/header"
import { aboutMeData } from "./data/data"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header data={aboutMeData}/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
